Added cobra, auth skel
planrockr/planrockr-cli pull request #8
Opened 2017-02-07 15:42 UTC by eminetto

Connected to #4

2017-02-07 15:59 UTC, lucassabreu commented on scripts/ci.sh
> +# go test ./cmd/...
script vazio?

2017-02-07 16:00 UTC, lucassabreu commented on src/github.com/planrockr/planrockr-cli/cmd/auth.go
> +		//@todo: save on ~/.planrockr-cli.yaml
não seria melhor deixar uma issue?

2017-02-07 16:18 UTC, lucassabreu commented on src/github.com/planrockr/planrockr-cli/cmd/auth.go
> +	body := strings.NewReader("parameters%5Blogin%5D=" + user + "&parameters%5Bpassword%5D=" + password)
a api do planrocker suportar o json acho que talvez fique com menos scapes o comando

2017-02-07 16:20 UTC, eminetto commented on scripts/ci.sh
> +# go test ./cmd/...
Somente até implementarmos os testes, senão o Travis quebra :(

2017-02-07 16:20 UTC, lucassabreu commented on src/github.com/planrockr/planrockr-cli/cmd/import.go
> +This application is a tool to generate the needed files
esta com o `Long` padrão aqui

2017-02-07 16:21 UTC, eminetto commented on src/github.com/planrockr/planrockr-cli/cmd/auth.go
> +	body := strings.NewReader("parameters%5Blogin%5D=" + user + "&parameters%5Bpassword%5D=" + password)
Por enquanto não suporta, mas eu vou precisar fazer uma melhoria no backend do Planrockr para aceitar as importações, aí refatoro isso tmb

2017-02-07 16:21 UTC, eminetto commented on src/github.com/planrockr/planrockr-cli/cmd/import.go
> +This application is a tool to generate the needed files
Sim, vou mudar isso na tarefa específica do Import

2017-02-07 16:31 UTC, lucassabreu commented
o git quando baixa os repositórios tbm faz o download dos "módulos" internos? ou tem de usar um `git clone`, `git pull` diferenciado? se tiver era bom colocar no `README.md` como fazer isso, eu acho
Outra coisa não tem chance de alguma dependência das dependências não vir junto quando faz desse jeito?

2017-02-08 12:43 UTC, leandro-lugaresi requested changes
Essa estrutura de pacotes e diretórios está muito confusa.
A nossa estrutura deveria ser a seguinte (já considerando o uso do cobra para os comandos do cli):
```
/
   README.md
   Makefile
   auth.go
   foo.go
   main.go
   cmd
      cmd01.go
      cmd02.go
```
Dessa forma, quando for utilizado com o `go get` e nos imports a seguinte estrutura será criada/utilizada:
```
$GOPATH/
    src/
        github.com/
            planrockr/
                planrockr-cli/
                    .git/
                    README.md
                    Makefile
                    auth.go
                    foo.go
                    main.go
                    cmd
                       cmd01.go
                       cmd02.go
                    vendor
                       ...
             some-user
                uselessd/
                    .git/
                    uselessd.go
                    uselessd_test.go
                    README.md
```

O processo de setup para desenvolvimento seria o seguinte (para o setup com um $GOPATH único):
```
mkdir -p $GOPATH/src/github.com/planrockr
cd $GOPATH/src/github.com/planrockr 
git clone https://github.com/planrockr/planrockr-cli.git
cd planrockr-cli
```
Caso queira trabalhar com mais de um GOPATH, temos duas opções:
 - Setar o $GOPATH para outro diretório e executar os passos acima.
- Utilizar a estrutura proposta pelo pessoal da Cloudflare. [https://github.com/cloudflare/hellogopher](https://github.com/cloudflare/hellogopher)

2017-02-08 15:17 UTC, eminetto commented
@leandro-lugaresi fiz a mudança sugerida, para ficar de acordo com o https://github.com/cloudflare/hellogopher. 
Eu acho meio estranho commitar o vendor, mas eles sugerem isso e o https://github.com/digitalocean/doctl tmb está fazendo dessa forma, então parece ser uma trend :)

2017-02-08 15:53 UTC, leandro-lugaresi approved these changes

2017-02-08 15:55 UTC, leandro-lugaresi commented
Se você acha muito ruim ficar enviando o vendor nos PRs por dificultar um pouco os reviews, podemos commitar o vendor somente quando chegarmos na versão 1.0

2017-02-08 16:04 UTC, merged